-- KHACHHANG - 21-Group
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,1,2,1,1) -- hs HCMC
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,2,2,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,1,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,3,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,1,3,1,1) -- sv HCMC
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,1,3,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,1,3,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,1,3,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,1,3,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,1,3,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,1,1,1,2) -- hs HNC
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,2,1,0,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,5,2,1,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,4,2,0,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,3,0,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,1,3,1,2) -- sv HNC
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,0,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,4,3,0,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,1,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,4,1,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,1,1,0,52) -- hs Can Tho
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,2,1,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,4,2,0,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,5,2,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,3,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,1,3,0,52) -- sv Can tho
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,4,3,0,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,1,2,0,1) -- hs tinh khac
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,2,2,1,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,3) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,4,2,1,4)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,5,2,0,5) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,2,2,1,6)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,5,2,1,7)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,2,2,0,8)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,5,2,1,9)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,2,2,0,10)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,5,2,0,11)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,2,2,1,12) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,5,2,0,13)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,2,2,1,14) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,2,2,1,15)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,2,2,0,16)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,5,2,1,17)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,5,2,1,18)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,5,1,0,19)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,1,1,20)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,1,1,21) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,3,1,22)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,3,1,23) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,3,0,24)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,25)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,26)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,27)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,28)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,29)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,30) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,31)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,32) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,33)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,34)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,35)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,36)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,37)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,38)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,39) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,40)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,41) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,42)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,43)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,44)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,45)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,46)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,47)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,48) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,49)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,50)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,51) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,53)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,54)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,55)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,56)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,57)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,58) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,1,1,59)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,1,0,60)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,3,1,61) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,62)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,63)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,0,64)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (1,3,2,1,65)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,1,3,1,1) -- sv tinh khac 2
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,1,2)  
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,0,3) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,0,4)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,1,5) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,1,6) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,0,7)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,1,8)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,0,9)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,1,10)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,0,11)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,2,3,1,12) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,4,3,1,13)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,4,3,0,14) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,4,3,1,15)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,4,3,0,16)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,4,3,1,17)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,4,3,1,18)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,4,3,0,19)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,4,3,1,20)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,1,21) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,0,22)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,1,23) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,1,24)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,0,25)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,1,26)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,1,27)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,1,28)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,0,29)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,1,30) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,5,3,0,31)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,0,32) --sv lap trinh
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,1,33)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,1,34)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,0,35)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,1,36)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,1,37)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,0,38)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,1,39) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,1,40)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,0,41) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,1,42)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,1,43)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,8,3,0,44) --end sv lap trinh
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,45)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,46)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,47)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,48) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,49)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,50)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,51) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,53)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,54)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,55)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,56)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,57)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,58) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,59)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,60)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,61) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,62)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,63)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,64)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,4,1,65)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,1) -- sv tinh khac 3
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,4,0,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,3) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,4)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,5) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,6)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,7)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,8)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,9)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,10)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,11)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,12) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,13)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,14) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,4,1,15)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,16)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,17)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,18)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,19)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,20)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,21) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,22)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,23) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,24)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,25)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,26)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,27)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,28)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,29)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,30) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,31)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,32) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,33)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,34)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,35)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,36)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,37)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,38)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,39) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,40)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,41) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,42)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,43)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,44)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,45)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,46)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,47)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,48) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,49)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,50)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,51) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,53)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,54)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,55)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,56)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,57)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,58) 
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,0,59)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (2,3,3,1,60)

-- GIAO DICH - 21-Group
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (1,1,'11/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (2,1,'12/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (3,1,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (4,1,'07/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (5,1,'08/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (6,1,'09/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (7,1,'09/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (8,7,'10/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (9,8,'03/21/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (10,9,'03/21/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (11,9,'04/21/2002')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (12,8,'05/21/2003')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (13,7,'06/21/2004')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (14,1,'07/21/2005')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (15,1,'08/21/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (16,16,'09/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (17,17,'10/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (18,18,'11/01/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (19,1,'12/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (20,1,'01/21/2003')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (21,2,'02/21/2004')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (22,2,'03/21/2005')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (23,2,'04/22/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (24,2,'05/21/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (25,2,'03/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (26,2,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (27,2,'02/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (28,2,'02/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (29,2,'02/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (30,2,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (31,3,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (32,3,'08/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (33,3,'03/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (34,3,'03/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (35,3,'03/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (36,3,'03/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (37,3,'03/21/2007')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (38,3,'03/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (39,3,'03/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (40,3,'03/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (41,3,'05/09/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (42,3,'04/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (43,3,'06/07/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (44,3,'07/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (45,3,'08/04/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (46,3,'03/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (47,3,'03/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (48,3,'03/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (49,3,'03/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (50,3,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (51,4,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (52,4,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (53,4,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (54,4,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (55,4,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (56,5,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (57,5,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (58,5,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (59,5,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (60,6,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (61,6,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (62,6,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (63,6,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (64,6,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (65,6,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (66,6,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (67,6,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (68,6,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (69,6,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (70,6,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (71,6,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (72,6,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (73,6,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (74,6,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (75,6,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (76,6,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (77,6,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (78,6,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (79,6,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (80,6,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (81,2,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (82,2,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (83,2,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (84,2,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (85,2,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (86,2,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (87,2,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (88,2,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (89,7,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (90,8'11/12/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (91,9,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (92,2,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (93,2,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (94,2,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (95,2,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (96,10,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (97,10,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (98,10,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (99,10,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (100,10,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (101,11,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (102,11,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (103,11,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (104,11,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (105,11,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (106,12,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (107,12,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (108,12,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (109,12,'12/11/2010') 
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (110,13,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (111,13,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (112,13,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (113,13,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (114,13,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (115,13,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (116,13,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (117,13,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (118,13,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (119,13,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (120,13,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (121,14,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (122,14,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (123,14,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (124,14,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (125,14,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (126,14,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (127,15,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (128,15,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (129,15,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (130,15,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (131,15,'01/21/2008') 
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (132,15,'02/21/2009') 
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (133,15,'05/21/2010') 
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (134,19,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (135,19,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (136,19,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (137,19,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (138,19,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (139,20,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (140,20,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (141,20,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (142,20,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (143,20,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (144,20,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (145,21,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (146,21,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (147,21,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (148,21,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (149,21,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (150,21,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (151,21,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (152,21,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (153,21,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (154,21,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (155,21,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (156,22,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (157,22,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (158,2,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (159,4,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (160,5,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (161,2,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (162,4,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (163,5,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (164,2,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (165,4,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (166,5,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (167,2,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (168,4,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (169,5,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (170,2,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (171,22,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (172,22,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (173,22,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (174,22,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (175,22,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (176,22,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (177,22,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (178,23,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (179,23,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (180,23,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (181,23,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (182,23,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (183,23,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (184,23,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (185,23,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (186,23,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (187,23,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (188,23,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (189,23,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (190,24,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (191,24,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (192,24,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (193,24,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (194,25,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (195,25,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (196,25,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (197,25,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (198,25,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (199,26,'12/11/2010') 
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (200,27,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (201,27,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (202,27,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (203,27,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (204,27,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (205,27,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (206,28,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (207,28,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (208,28,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (209,28,'12/11/2010') 
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (210,29,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (211,30,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (212,30,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (213,30,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (214,30,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (215,30,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (216,30,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (217,30,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (218,30,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (219,30,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (220,30,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (221,30,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (222,31,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (223,31,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (224,31,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (225,31,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (226,31,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (227,31,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (228,31,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (229,31,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (230,31,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (231,31,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (232,31,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (233,31,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (234,1,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (235,1,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (236,1,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (237,1,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (238,13,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (239,13,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (240,13,'11/12/2006')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (241,13,'01/21/2008')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (242,13,'02/21/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (243,13,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (244,13,'06/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (245,13,'07/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (246,13,'01/01/2001')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (247,13,'02/20/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (248,13,'03/26/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (249,13,'12/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values (250,13,'11/12/2006')