insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,9,5,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,5,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,9,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,9,5,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,6,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,40)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,5,0,41)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,9,5,1,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,43)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,44)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,0,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,46)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,0,47)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,48)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,49)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,1,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,4)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,6)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,7)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,1,8)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,1,9)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,10)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,11)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,12)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,1,13)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,14)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,11,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,17)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,1,18)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,1,19)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,0,11)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,22)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,1,23)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,24)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,25)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,26)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,27)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,1,28)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,1,29)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,30)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,31)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,32)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,1,33)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,34)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,35)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,36)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,37)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,1,38)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,1,39)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,40)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,41)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,1,43)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,44)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,46)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,47)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,1,48)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,1,49)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,50)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,51)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,52)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,1,53)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,54)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,55)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,56)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,57)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,1,58)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,1,59)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,60)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,61)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,62)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,1,63)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,64)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,65)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,1,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,1,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,5,4,1,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,1,115)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,4,0,115)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,3,5,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,2,5,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (3,12,4,1,116)
--BS
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,9,5,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,9,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,9,5,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,40)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,5,0,41)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,9,5,1,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,43)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,44)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,0,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,46)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,0,47)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,48)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,49)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,1,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,4)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,6)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,7)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,1,8)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,1,9)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,10)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,11)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,12)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,1,13)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,14)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,11,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,17)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,1,18)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,1,19)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,11)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,22)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,1,23)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,24)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,25)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,26)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,27)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,1,28)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,1,29)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,30)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,31)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,32)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,1,33)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,34)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,35)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,36)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,37)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,1,38)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,1,39)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,40)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,41)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,1,43)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,44)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,0,46)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,5,0,47)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,1,48)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,1,49)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,50)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,5,1,51)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,52)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,1,53)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,54)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,55)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,56)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,57)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,1,58)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,1,59)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,60)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,61)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,62)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,1,63)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,64)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,65)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,1,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,1,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,5,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,5,4,1,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,1,115)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,4,0,115)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,3,5,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,2,4,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (4,12,4,1,116)
--GiaoDich
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 251,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 252,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 253,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 254,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 255,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 256,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 257,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 258,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 259,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 260,32,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 261,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 262,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 263,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 264,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 265,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 266,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 267,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 268,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 269,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 270,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 271,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 272,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 273,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 274,22,'01/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 275,22,'01/30/2011')

insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 276,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 277,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 278,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 279,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 280,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 281,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 282,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 283,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 284,32,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 285,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 286,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 287,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 288,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 289,29,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 290,32,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 291,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 292,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 293,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 294,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 295,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 296,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 297,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 298,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 299,30,'01/31/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 300,30,'01/31/2011')

insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 301,29,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 302,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 303,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 304,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 305,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 306,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 307,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 308,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 309,32,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 310,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 311,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 312,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 313,32,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 314,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 315,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 316,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 317,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 318,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 319,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 320,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 321,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 322,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 323,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 324,23,'02/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 325,32,'02/02/2011')

insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 326,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 327,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 328,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 329,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 330,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 331,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 332,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 333,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 334,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 335,32,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 336,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 337,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 338,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 339,32,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 340,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 341,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 342,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 343,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 344,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 345,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 346,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 347,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 348,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 349,21,'02/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 350,21,'02/08/2011')

insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 351,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 352,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 353,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 354,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 355,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 356,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 357,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 358,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 359,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 360,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 361,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 362,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 363,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 364,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 365,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 366,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 367,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 368,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 369,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 370,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 371,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 372,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 373,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 374,27,'02/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 375,27,'02/10/2011')

insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 376,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 377,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 378,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 379,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 380,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 381,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 382,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 383,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 384,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 385,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 386,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 387,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 388,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 389,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 390,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 391,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 392,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 393,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 394,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 395,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 396,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 397,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 398,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 399,26,'02/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 400,26,'02/13/2011')

insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 401,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 402,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 403,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 404,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 405,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 406,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 407,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 408,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 409,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 410,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 411,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 412,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 413,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 414,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 415,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 416,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 417,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 418,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 419,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 420,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 421,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 422,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 423,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 424,20,'02/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 425,20,'02/17/2011')

insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 426,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 427,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 428,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 429,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 430,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 431,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 432,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 433,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 434,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 435,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 436,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 437,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 438,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 439,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 440,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 441,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 442,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 443,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 444,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 445,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 446,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 447,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 448,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 449,24,'02/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 450,24,'02/19/2011')

insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 451,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 452,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 453,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 454,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 455,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 456,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 457,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 458,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 459,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 460,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 461,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 462,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 463,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 464,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 465,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 466,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 467,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 468,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 469,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 470,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 471,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 472,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 473,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 474,31,'02/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 475,31,'02/24/2011')

insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 476,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 477,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 478,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 479,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 480,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 481,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 482,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 483,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 484,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 485,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 486,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 487,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 488,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 489,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 490,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 491,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 492,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 493,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 494,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 495,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 496,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 497,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 498,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 599,25,'03/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 500,25,'03/04/2011')





