use ESTORE

--Nhap khach hang tu 751-1000. Thu tu theo muc dich su dung
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,1,4,1,10)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,1,4,0,11)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,1,4,1,14)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,1,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,1,4,1,4)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,1,4,0,7)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,1,4,0,17)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,1,4,1,30)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,1,4,1,20)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,1,4,0,21)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,1,4,1,24)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,1,4,0,27)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,1,4,0,51)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,1,5,0,55)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,1,6,0,59)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,2,4,1,60)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,2,6,1,56)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,2,5,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,2,5,1,28)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,2,5,0,25)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,2,5,1,22)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,2,5,1,18)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,2,5,1,8)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,2,5,0,5)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,2,5,1,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,2,5,0,15)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,2,5,1,12)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,3,6,0,13)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,3,6,0,9)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,3,6,0,23)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,3,6,1,26)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,3,6,0,29)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,3,6,1,16)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,3,6,0,19)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,3,6,0,53)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,3,4,0,57)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,5,1,58)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,4,1,54)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,6,0,46)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,4,1,47)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,5,0,30)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,6,1,31)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,4,0,38)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,5,1,39)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,6,0,22)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,4,1,23)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,4,0,14)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,5,1,15)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,6,1,7)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,4,0,14)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,5,1,15)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,6,0,22)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,4,1,23)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,6,1,7)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,5,0,30)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,6,1,31)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,6,0,46)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,4,1,47)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,4,0,38)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,5,1,39)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,4,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,4,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,5,4,0,51)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,5,5,1,52)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,5,6,0,53)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,5,4,1,54)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,5,5,0,55)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,5,6,1,56)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,5,4,0,57)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,5,5,1,58)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,5,6,0,59)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,5,4,1,60)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,6,0,40)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,4,0,32)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,5,1,45)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,4,1,29)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,6,1,37)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,5,0,48)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,5,0,48)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,6,0,40)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,5,1,45)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,6,1,37)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,4,0,32)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,6,0,16)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,4,0,8)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,5,1,21)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,5,0,6)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,4,1,29)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,6,1,13)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,5,0,24)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,5,0,24)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,6,0,16)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,4,0,8)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,6,1,61)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,5,0,6)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,6,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,6,1,13)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,5,1,21)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,6,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,4,1,65)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,4,0,62)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,5,1,9)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,5,0,12)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,4,0,20)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,4,1,17)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,6,0,28)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,4,0,20)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,5,0,12)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,5,1,9)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,4,1,5)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,4,0,2)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,4,1,17)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,6,1,25)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,5,1,33)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,5,0,36)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,4,1,41)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,4,0,44)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,6,1,49)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,6,1,49)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,6,0,28)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,6,1,25)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,5,1,33)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,5,0,36)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,7,4,1,41)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,7,4,0,44)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,5,0,42)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,6,1,43)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,6,0,34)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,4,1,35)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,4,0,26)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,5,1,27)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,4,0,50)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,5,0,42)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,6,1,43)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,4,0,50)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,6,0,34)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,4,1,35)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,4,0,26)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,5,1,27)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,5,0,18)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,6,1,19)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,5,1,3)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,6,0,4)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,6,0,10)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,4,1,11)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,5,0,18)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,6,1,19)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,6,0,10)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,4,1,11)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,5,1,63)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,6,0,64)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,5,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,4,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,6,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,4,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,5,0,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,6,1,1)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,6,0,3)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,4,1,4)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (8,8,5,0,5)
insert into KhachHang(MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (7,8,6,1,6)

--Nhap vao bang giao dich tuong ung voi khach hang
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 751,5,'03/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 752,11,'03/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 753,21,'03/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 754,23,'03/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 755,25,'03/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 756,5,'03/22/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 757,11,'03/22/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 758,21,'03/22/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 759,23,'03/22/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 760,25,'03/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 761,5,'03/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 762,11,'03/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 763,21,'03/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 764,23,'03/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 765,25,'03/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 766,12,'03/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 767,13,'03/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 768,20,'03/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 769,22,'03/28/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 770,24,'03/28/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 771,30,'03/28/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 772,12,'03/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 773,13,'03/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 774,20,'03/30/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 775,22,'04/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 776,24,'04/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 777,30,'04/02/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 778,21,'04/03/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 779,22,'04/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 780,23,'04/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 781,25,'04/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 782,21,'04/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 783,22,'04/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 784,23,'04/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 785,25,'04/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 786,21,'04/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 787,1,'04/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 788,3,'04/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 789,6,'04/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 790,13,'04/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 791,22,'04/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 792,1,'04/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 793,3,'04/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 794,6,'04/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 795,13,'04/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 796,22,'04/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 797,1,'04/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 798,3,'04/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 799,6,'04/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 800,13,'04/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 801,22,'04/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 802,1,'04/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 803,3,'04/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 804,6,'04/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 805,13,'04/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 806,22,'04/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 807,22,'04/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 808,13,'04/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 809,1,'04/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 810,6,'04/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 811,3,'04/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 812,3,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 813,3,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 814,6,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 815,1,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 816,13,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 817,13,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 818,22,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 819,6,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 820,3,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 821,1,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 822,22,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 823,13,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 824,1,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 825,3,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 826,6,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 827,13,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 828,22,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 829,1,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 830,6,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 831,3,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 832,22,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 833,13,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 834,22,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 835,1,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 836,6,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 837,7,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 838,8,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 839,9,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 840,16,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 841,17,'04/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 842,18,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 843,9,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 844,8,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 845,7,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 846,16,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 847,7,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 848,8,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 849,9,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 850,16,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 851,17,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 852,18,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 853,32,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 854,7,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 855,9,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 856,8,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 857,16,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 858,18,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 859,32,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 860,32,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 861,7,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 862,9,'04/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 863,9,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 864,18,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 865,16,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 866,16,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 867,32,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 868,7,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 869,7,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 870,7,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 871,8,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 872,16,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 873,18,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 874,9,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 875,17,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 876,7,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 877,8,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 878,9,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 879,16,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 880,17,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 881,18,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 882,32,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 883,17,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 884,16,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 885,18,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 886,7,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 887,8,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 888,32,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 889,9,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 890,9,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 891,7,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 892,8,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 893,9,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 894,16,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 895,7,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 896,18,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 897,11,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 898,14,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 899,26,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 900,27,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 901,28,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 902,26,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 903,26,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 904,11,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 905,14,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 906,14,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 907,11,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 908,28,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 909,27,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 910,11,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 911,14,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 912,14,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 913,26,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 914,27,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 915,28,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 916,28,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 917,28,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 918,27,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 919,27,'04/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 920,26,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 921,11,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 922,11,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 923,11,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 924,11,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 925,14,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 926,26,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 927,27,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 928,27,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 929,27,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 930,28,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 931,28,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 932,28,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 933,14,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 934,11,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 935,26,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 936,27,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 937,27,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 938,28,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 939,26,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 940,11,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 941,14,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 942,26,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 943,27,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 944,28,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 945,27,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 946,26,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 947,2,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 948,11,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 949,15,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 950,20,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 951,24,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 952,20,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 953,20,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 954,24,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 955,2,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 956,11,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 957,2,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 958,2,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 959,2,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 960,15,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 961,20,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 962,24,'04/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 963,24,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 964,24,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 965,20,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 966,20,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 967,11,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 968,2,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 969,2,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 970,15,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 971,20,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 972,2,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 973,11,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 974,11,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 975,15,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 976,15,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 977,20,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 978,2,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 979,2,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 980,2,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 981,24,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 982,11,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 983,15,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 984,20,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 985,20,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 986,24,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 987,24,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 988,2,'04/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 989,2,'04/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 990,11,'04/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 991,15,'04/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 992,20,'04/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 993,24,'04/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 994,2,'04/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 995,11,'04/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 996,15,'04/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 997,20,'04/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 998,24,'04/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 999,2,'04/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 1000,11,'04/19/2011')