<?xml version="1.0" encoding="utf-8"?>
<Database Name="ESTORE" Class="EStoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=ESTORE;Integrated Security=True" SettingsObjectName="EStoreDAO.Properties.Settings" SettingsPropertyName="ESTOREConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NHASANXUAT" Member="NHASANXUATs">
    <Type Name="NHASANXUAT">
      <Column Name="MaNhaSanXuat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhaSanXuat" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="NHASANXUAT_CHITIETDONGLAPTOP" Member="CHITIETDONGLAPTOPs" OtherKey="MaNhaSanXuat" Type="CHITIETDONGLAPTOP" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDONGLAPTOP" Member="CHITIETDONGLAPTOPs">
    <Type Name="CHITIETDONGLAPTOP">
      <Column Name="MaDongLapTop" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChiTietDongLapTop" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MaDongRAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDongCPU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDongOCung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDongManHinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDongCardDoHoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDongLoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDongODiaQuang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDongCardMang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDongCardReader" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDongWebCam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDongPin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHeDieuHanh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChiTietTrongLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FingerprintReader" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HDMI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoLuongCongUSB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhaSanXuat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDanhGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBanHienHanh" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MoTaThem" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="SoLuongNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongConLai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianBaoHanh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MauSac" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="NHASANXUAT_CHITIETDONGLAPTOP" Member="NHASANXUAT" ThisKey="MaNhaSanXuat" Type="NHASANXUAT" IsForeignKey="true" />
    </Type>
  </Table>
</Database>