-- Bang Khach hang
-- Duoc si
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,5,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,5,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,6,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,0,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,4,1,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,6,0,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,0,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,5,1,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,4)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,6,1,4)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,6,0,4)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,4)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,0,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,6,1,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,30)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,0,33)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,5,1,33)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,1,32)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,4,1,32)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,0,33)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,0,35)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,0,35)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,4,1,35)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,35)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,1,7)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,7)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,1,7)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,7)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,6,1,6)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,6)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,0,7)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,1,8)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,1,9)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,12)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,1,13)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,12)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,1,11)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,14)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,4,11,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,0,17)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,1,18)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,1,19)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,0,11)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,22)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,1,23)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,24)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,4,1,25)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,26)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,27)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,6,1,28)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,1,29)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,30)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,1,31)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,32)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,1,33)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,34)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,6,1,35)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,36)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,37)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,1,38)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,1,39)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,40)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,1,41)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,1,43)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,44)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,4,1,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,46)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,0,47)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,1,48)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,1,49)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,50)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,6,1,51)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,52)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,1,53)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,54)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,1,55)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,56)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,57)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,1,58)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,1,59)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,60)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,61)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,62)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,1,63)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,64)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,4,1,65)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,1,77)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,1,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,1,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,4,4,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,5,4,1,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,1,115)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,0,115)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,5,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,2,5,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (5,3,4,1,116)
--Ky su xay dung
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,5,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,5,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,40)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,5,1,41)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,5,1,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,43)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,44)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,46)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,47)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,48)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,49)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,4)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,6)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,4,0,7)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,8)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,9)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,10)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,11)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,4,1,12)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,13)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,4,1,14)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,17)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,18)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,19)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,0,11)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,2)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,0,22)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,23)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,24)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,25)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,26)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,27)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,28)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,29)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,30)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,31)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,32)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,33)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,34)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,35)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,36)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,37)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,38)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,39)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,0,40)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,41)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,0,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,5,1,43)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,44)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,46)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,5,0,47)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,48)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,5,1,49)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,50)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,5,1,51)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,52)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,53)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,54)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,55)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,56)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,57)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,58)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,59)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,0,60)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,61)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,62)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,63)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,64)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,65)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,79)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,79)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,79)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,79)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,79)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,80)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,80)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,80)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,75)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,0,75)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,0,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,116)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,5,1,10)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,110)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,15)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,0,115)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,18)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,11)
-- Bang Giao dich
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 501,21,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 502,23,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 503,22,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 504,33,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 505,20,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 506,34,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 507,24,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 508,25,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 509,25,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 510,25,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 511,24,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 512,26,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 513,24,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 514,24,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 515,24,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 516,24,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 517,20,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 518,21,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 519,21,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 520,21,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 521,22,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 522,22,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 523,22,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 524,23,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 525,23,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 526,23,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 527,24,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 528,20,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 529,20,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 530,20,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 531,24,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 532,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 533,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 534,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 535,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 536,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 537,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 538,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 539,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 540,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 541,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 542,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 543,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 544,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 545,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 546,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 547,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 548,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 549,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 550,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 551,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 552,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 553,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 554,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 555,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 556,31,'03/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 557,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 558,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 559,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 560,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 561,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 562,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 563,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 564,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 565,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 566,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 567,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 568,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 569,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 570,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 571,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 572,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 573,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 574,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 575,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 576,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 577,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 578,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 579,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 580,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 581,25,'03/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 582,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 583,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 584,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 585,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 586,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 587,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 588,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 589,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 590,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 591,32,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 592,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 593,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 594,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 595,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 596,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 597,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 598,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 599,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 600,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 601,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 602,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 603,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 604,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 605,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 606,22,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 607,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 608,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 609,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 610,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 611,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 612,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 613,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 614,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 615,32,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 616,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 617,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 618,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 619,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 620,29,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 621,32,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 622,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 623,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 624,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 625,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 626,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 627,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 628,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 629,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 630,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 631,30,'03/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 632,29,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 633,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 634,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 635,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 636,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 637,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 638,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 639,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 640,32,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 641,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 642,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 643,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 644,32,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 645,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 646,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 647,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 648,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 649,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 650,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 651,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 652,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 653,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 654,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 655,23,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 656,32,'03/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 657,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 658,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 659,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 660,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 661,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 662,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 663,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 664,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 665,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 666,32,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 667,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 668,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 669,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 670,32,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 671,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 672,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 673,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 674,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 675,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 676,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 677,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 678,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 679,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 680,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 681,21,'03/09/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 682,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 683,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 684,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 685,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 686,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 687,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 688,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 689,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 690,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 691,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 692,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 693,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 694,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 695,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 696,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 697,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 698,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 699,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 700,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 701,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 702,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 703,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 704,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 705,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 706,27,'03/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 707,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 708,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 709,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 710,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 711,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 712,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 713,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 714,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 715,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 716,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 717,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 718,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 719,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 720,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 721,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 722,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 723,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 724,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 725,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 726,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 727,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 728,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 729,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 730,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 731,26,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 732,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 733,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 734,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 735,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 736,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 737,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 738,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 739,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 740,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 741,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 742,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 743,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 744,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 745,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 746,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 747,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 748,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 749,20,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 750,20,'03/12/2011')


