insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,0,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,6,0,22)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,6,0,57)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,5,0,57)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,6,1,46)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,5,1,39)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,6,1,27)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,6,0,41)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,5,0,50)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,0,51)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,6,0,30)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,15)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,6,0,33)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,5,1,62)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,6,0,1)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,4,1,18)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,4,1,54)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,5,0,34)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,6,0,54)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,0,15)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,6,1,12)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,5,0,56)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,6,0,62)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,5,1,10)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,6,0,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,5,1,25)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,13)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,6,1,43)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,5,0,52)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,6,0,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,33)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,6,1,43)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,39)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,6,0,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,6,0,51)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,6,1,7)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,5,1,27)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,6,1,14)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,6,0,37)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,5,0,38)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,5,1,47)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,4,1,40)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,6,1,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,5,1,28)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,6,1,33)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,5,1,26)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,4,0,59)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,6,0,56)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,5,0,8)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,4,0,28)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,0,58)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,1,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,6,1,26)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,5,1,49)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,0,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,6,0,4)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,1,15)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,4,1,38)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,6,1,59)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,5,0,6)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,6,0,9)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,0,39)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,36)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,6,0,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,5,0,29)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,5,1,36)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,5,1,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,6,0,22)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,6,0,31)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,5,1,27)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,1,25)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,6,0,22)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,6,0,21)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,5,0,61)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,0,46)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,6,1,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,5,0,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,5,1,9)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,0,57)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,6,1,62)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,6,1,46)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,5,0,27)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,5,1,10)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,4,1,58)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,0,35)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,22)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,4,0,36)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,0,53)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,6,1,14)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,5,1,56)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,5,0,58)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,6,0,62)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,47)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,6,0,22)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,5,1,52)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,6,0,47)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,17)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,4,1,25)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,6,1,46)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,5,1,58)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,1,44)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,6,0,45)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,5,1,49)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,5,1,58)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,6,0,24)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,6,0,37)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,5,1,50)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,5,0,7)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,4,1,56)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,6,0,12)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,5,0,9)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,6,1,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,6)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,38)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,5,0,44)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,5,1,9)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,0,34)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,6,1,35)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,4,1,37)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,5,0,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,5,1,52)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,6,0,10)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,4,0,61)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,5,1,8)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,0,35)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,19)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,0,36)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,6,1,40)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,4,0,51)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,6,1,51)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,4,0,14)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,5,1,55)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,1,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,5,6,1,48)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,0,13)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,5,1,13)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,5,1,60)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,1,31)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,6,0,20)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,4,0,17)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,4,1,11)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,6,0,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,4,0,16)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,7,4,0,37)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,0,43)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,6,1,5)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,5,1,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,6,1,58)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,4,0,40)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,4,5,0,37)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,5,1,29)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,6,0,17)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,4,0,43)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,2,4,0,8)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,1,4,1,3)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,1,48)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,3,4,1,60)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,8,5,0,42)
insert into KhachHang(	MaNgheNghiep, MaMucDichSuDung, MaDoTuoi, GioiTinhNam, MaTinhThanh)values (6,6,5,0,56)

select * from khachhang


insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 580,4,'02/10/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 581,3,'03/11/2009')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 582,4,'04/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 583,3,'05/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 584,3,'06/18/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 585,1,'07/24/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 586,4,'08/27/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 587,2,'09/28/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 588,4,'10/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 589,3,'02/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 590,2,'03/22/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 591,3,'07/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 592,3,'03/28/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 593,2,'04/23/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 594,4,'07/20/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 595,2,'06/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 596,1,'02/23/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 597,3,'06/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 598,4,'02/28/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 599,3,'07/15/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 600,1,'03/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 601,2,'05/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 602,1,'07/26/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 603,4,'08/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 604,2,'09/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 605,4,'04/20/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 606,3,'05/06/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 607,3,'07/08/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 608,1,'03/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 609,3,'05/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 610,2,'07/26/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 611,3,'08/29/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 612,4,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 613,4,'06/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 614,1,'07/19/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 615,1,'08/04/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 616,3,'09/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 617,2,'05/07/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 618,3,'07/04/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 619,2,'08/06/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 620,2,'12/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 621,1,'11/25/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 622,2,'11/05/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 623,4,'11/01/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 624,4,'12/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 625,1,'12/16/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 626,2,'11/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 627,4,'10/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 628,2,'06/27/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 629,4,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 630,4,'07/12/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 631,1,'09/13/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 632,3,'09/14/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 633,1,'03/15/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 634,3,'06/16/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 635,2,'04/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 636,2,'07/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 637,2,'09/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 638,3,'03/25/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 639,4,'07/26/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 640,1,'08/27/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 641,1,'03/28/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 642,1,'08/22/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 643,4,'04/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 644,1,'07/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 645,2,'03/25/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 646,2,'07/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 647,4,'03/27/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 648,1,'08/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 649,4,'05/22/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 650,3,'07/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 651,4,'08/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 652,4,'09/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 653,1,'10/25/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 654,3,'05/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 655,3,'03/27/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 656,1,'06/27/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 657,3,'08/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 658,3,'02/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 659,1,'02/14/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 660,1,'02/16/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 661,1,'02/17/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 662,3,'05/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 663,3,'10/19/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 664,3,'12/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 665,1,'11/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 666,2,'06/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 667,1,'08/11/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 668,2,'09/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 669,3,'03/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 670,4,'05/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 671,4,'06/11/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 672,1,'07/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 673,1,'09/27/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 674,2,'04/28/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 675,4,'06/29/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 676,3,'07/20/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 677,4,'08/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 678,2,'09/22/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 679,3,'03/25/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 680,2,'05/26/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 681,4,'06/27/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 682,3,'07/28/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 683,3,'08/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 684,4,'09/25/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 685,4,'05/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 686,3,'06/27/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 687,4,'07/28/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 688,2,'08/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 689,4,'08/26/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 690,3,'09/27/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 691,2,'05/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 692,1,'07/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 693,2,'07/25/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 694,3,'08/26/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 695,2,'09/27/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 696,2,'04/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 697,2,'07/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 698,2,'08/24/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 699,2,'09/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 700,2,'04/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 701,1,'06/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 702,4,'06/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 703,2,'07/26/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 704,1,'08/28/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 705,1,'09/29/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 706,2,'03/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 707,4,'13/20/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 708,2,'12/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 709,3,'11/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 710,2,'03/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 711,3,'03/25/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 712,4,'03/23/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 713,4,'02/25/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 714,1,'03/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 715,4,'04/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 716,4,'05/12/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 717,4,'06/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 718,4,'07/17/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 719,1,'08/18/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 720,3,'09/19/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 721,4,'10/10/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 722,2,'11/12/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 723,2,'12/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 724,2,'05/21/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 725,3,'06/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 726,2,'07/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 727,1,'08/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 728,2,'09/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 729,4,'10/26/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 730,3,'04/28/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 731,1,'03/24/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 732,1,'03/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 733,2,'03/28/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 734,1,'03/29/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 735,2,'03/20/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 736,2,'02/21/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 737,3,'04/23/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 738,2,'05/25/2010')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 739,3,'06/26/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 740,3,'07/27/2011')
insert into GiaoDich(MaKhachHang, MaDongLapTop, NgayMua)values ( 741,1,'08/28/2011')
